version: 'X'

services:
  bot:
    build: .
  postgres:
    image: postgres
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORTS}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  postgres-data: