name: Docker Build and Run Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Environment File
      run: |
        echo "TOKEN=${{ secrets.TELEGRAM_TOKEN }}" > .env

    - name: Build Docker Image
      run: docker build -t telegram_bot_docker .

    - name: Run Docker Container
      run: |
        docker run -d --name telegram_bot -e STATUS_FILE_PATH=/tmp/bot_status.txt telegram_bot_docker
        
    - name: Sleep For a Short Time
      run: sleep 30s  # Wait for a short time to let the bot start

    - name: Check Status File for Bot Start
      run: |
        if docker exec telegram_bot [ -f /tmp/bot_status.txt ]; then
          echo "Bot started successfully"
          docker stop telegram_bot
        else
          echo "Bot did not start successfully"
          docker logs telegram_bot  # Print the logs for debugging
          exit 1
        fi
